[package]
name = "mathhammer"
version = "0.0.1"
authors = ["valarauca <codylaeder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cfgrammar = "0.7.0"
lrlex = "0.7.0"
lrpar = "0.7.0"

[dependencies]
cfgrammar = "0.7.0"
lrlex = "0.7.0"
lrpar = "0.7.0"
num-traits = "0.2.11"

